# Generated by Django 3.0.7 on 2020-06-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_criacao_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='matricula',
            new_name='turma',
        ),
    ]
